### ISSUE TITLE
Couldn't get this work on the installer

### ISSUE THREAD

**Issue by thepenguinthatwants** [StarlitGhost/selfhost-ttrss#1]
I tried to get your image to work on my local traefik setup.

The docker-compose file consist this 
```
version: '3.5'

services:
  ttrss:
    image: linuxserver/tt-rss:latest
    container_name: ttrss
    depends_on:
      - postgres
    networks:
      - srv
      - internal
    ports:
      - 8455:80
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      # - TZ=${TZ}
    volumes:
      - ${PERSISTENT_DIR}/config:/config
    labels:
      - "traefik.docker.network=srv"
      - "traefik.enable=true"
      - "traefik.backend=ttrss"
      - "traefik.frontend.rule=Host:rss.${DOMAIN_BASE}"
      - "traefik.port=80"
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: postgres
    networks:
      - internal
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      # - TZ=${TZ}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=ttrss
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pg-data:

networks:
  srv:
    external: true
  internal:
```
The .env file consists
```
PUID=1000
PGID=1000
DOMAIN_BASE=localhost
POSTGRES_USER=foo
POSTGRES_PW=bar
PERSISTENT_DIR=./test
```

After going to rss.localhost and filling the information I get this Error
```
SQLSTATE[08006] [7] could not connect to server: No such file or directory Is the server running locally and accepting connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

Unable to connect to database using specified parameters (driver: pgsql).
```

Does the PSQL runs at port 5432? Or is there something that should also be done to get this work?
